name = "Introduction2AmplitudeAnalysis"
uuid = "2f6f369f-6677-41f1-b09c-77f553d221a8"
authors = ["Misha Mikhasenko <mikhail.mikhasenko@gmail.com>"]
version = "0.0.1"

[deps]
Cuba = "8a292aeb-7a57-582c-b821-06e4c11590b1"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
InstantiateFromURL = "43edad99-fa64-5e4f-9937-1c09a410b73f"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PartialWaveFunctions = "793d2195-304b-438e-bbb1-bc33c872ac39"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
ThreeBodyDecay = "e6563dab-9ca1-5843-bde3-2ccf38d63843"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
UpROOT = "69ce31c6-c38d-56c2-aa87-409d3de9f997"

[compat]
julia = "1.5"
